### ISSUE TITLE
How to handle irtviewers and simulators in multiple nodes which use roseus?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_roseus#260]
In my project, I'm using roseus in multiple nodes to make robot's motion, and I launch these nodes with a launch file. The problem is that in each roseus programs run `(objects (list *robot*))` and __too many windows will open__.
I want the program to open simulator and irtviewer windows 

* only once and one window when they are launched

or

* each time when called from other programs and close the windows after that

**Comment by k-okada** [comment]
each roseus node has different instance of `*robot*` so sharing window over multiple roseus may difficult, my suggestion is to unset `DISPLAY` environment variable to disable windows as follows:
```
<launch>
  <arg name="GUI" default="true" />
  <env name="DISPLAY" value="" unless="$(arg GUI)"/>
  <node type="roseus" pkg="roseus" name="roseus"
        args="/home/k-okada/hoga.l" />
</launch>
```
and call
```
roslaunch hoga.launch  GUI:=false
```
or you may better to use
```
  <arg name="DEBUG" default="true" />
  <env name="DISPLAY" value="" if="$(arg DEBUG)"/>
```

**Comment by wkentaro** [comment]
Thanks a lot! It's what I'd like to do.

On Fri, Mar 13, 2015 at 9:36 AM, Kei Okada <notifications@github.com> wrote:

> each roseus node has different instance of *robot* so sharing window over
> multiple roseus may difficult, my suggestion is to unset DISPLAY
> environment variable to disable windows as follows:
>
> <launch>
>   <arg name="GUI" default="true" />
>   <env name="DISPLAY" value="" unless="$(arg GUI)"/>
>   <node type="roseus" pkg="roseus" name="roseus"
>         args="/home/k-okada/hoga.l" />
> </launch>
>
> and call
>
> roslaunch hoga.launch  GUI:=false
>
> or you may better to use
>
>   <arg name="DEBUG" default="true" />
>   <env name="DISPLAY" value="" if="$(arg DEBUG)"/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_roseus/issues/260#issuecomment-78717633>
> .
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
