### ISSUE TITLE
parallel state machineについて

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_roseus#310]
古田さんに書いていただいた、join の考えによるparallel state machine と、自分が書いたparallel state machine が実装は違うものの実現できることがかなりかぶってしまったように思っていますが、並列化の方法としてはやはりjoin を使ったものの方があるべき姿でしょうか？

同じことが出来るならばjoin 側だけに絞ったほうが良いでしょうか？

**Comment by k-okada** [comment]
止揚というコトバが有ります．これのドイツ語は何でしょう（100KP）

wikipediaあたりで勉強してもらったところで，ソフトウェア同じように発展していくのがいいですね．なので，いくつもの実装を見てよりよいものを残していく，というのがいいともいます．で途中で，もしかしたら，あそこでボツにした方法のほうが良かったんじゃない？というときにぱっと戻れるのがよいでしょう．

joinのときにand, orと考えられるけど，それぞれでどう書くのか，というのが見てみたいところでは有ります．


--
◉ Kei Okada


2015-05-08 11:34 GMT+09:00 h-kamada <notifications@github.com>:

**Comment by k-okada** [comment]
ところで，鎌田くんが書いたコードの PR番号はなに？

#309 は古田くんが書いたもののテストコードになっているのかな？

--
◉ Kei Okada


2015-05-08 20:12 GMT+09:00 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>:

**Comment by h-kamada** [comment]
いえ、　#308 は古田さんのtestコードを元に自分の並列state machine 用に書いたものです

**Comment by h-kamada** [comment]
ドイツ語ではアウフヘーベン、ヘーゲルの弁証法で用いられた概念ですね！
僕が書いた並列state-machineは #299 にあります。
古田さんの並列state-machine が先にmergeされているので、まずそのコードを自分のものと比較し、上手く自分のものとmerge出来ないか模索してみます。
