### ISSUE TITLE
ros::roseus-add-msgs hangs up if message contains 61 constants

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_roseus#313]
roseus cannot handle messages which contains over 61 constants.

https://github.com/garaemon/jsk_roseus/blob/msgs-bag/roseus/msg/String.msg

If you use the message above, `ros::roseus-add-msgs "roseus"` hangs up.

**Comment by garaemon** [comment]
https://gist.github.com/garaemon/73b9211513b16acad928
generated `roseus/ros/roseus/msg/String.l`

**Comment by garaemon** [comment]
`(shadow '*CONST62* (find-package "ROSEUS::STRING"))` does not return

**Comment by k-okada** [comment]
humm, simplest test code is -> https://gist.github.com/k-okada/eba5c9f10c63b0abb4bb
i'll look into it

**Comment by k-okada** [comment]
We need to expand https://github.com/euslisp/EusLisp/blob/master/lisp/c/eus.h#L143

**Comment by garaemon** [comment]
I'd like to increase it to 256 at least

**Comment by k-okada** [comment]
it seems there are a way to extend symbol vector 
```
64.eusgl$ make-package "hoge"
#<package #X6829728 hoge>
65.eusgl$ (length ((find-package "hoge") . intsymvector))
60
66.eusgl$ (length ((find-package "GEO") . intsymvector))
1828
67.eusgl$ (length ((find-package "USER") . intsymvector))
163
```

**Comment by k-okada** [comment]
```
(dotimes (i 100)
  (eval `(defconstant ,(intern (format nil "*CONST~d*" i)) i))))
(make-package "TEST1")
(dotimes (i 100)
  (eval `(defconstant ,(intern (format nil "TEST1::*CONST~d*" i)) i)))
(make-package "TEST2")
(dotimes (i 100)
  (catch 'error
    (labels ((error (&rest args) (apply #'format *error-output* args)(format *error-output* "~%")(throw 'error nil)))
      (shadow (intern (format nil "*CONST~d*" i)) (find-package "TEST2"))
      (eval `(defconstant ,(intern (format nil "TEST2::*CONST~d*" i)) i)))))
(make-package "TEST3")
(dotimes (i 100)
  (intern (format nil "*CONST~d*" i) (find-package "TEST3"))
  (shadow (intern (format nil "*CONST~d*" i)) (find-package "TEST3"))
  (eval `(defconstant ,(intern (format nil "TEST3::*CONST~d*" i)) i)))
```

**Comment by k-okada** [comment]
please try 
```
wget https://gist.githubusercontent.com/k-okada/b37a76caf73fd158cb80/raw/e67a0a2e56dd29f25c513e8e47e8e01ec882a228/gistfile1.txt -O - | bash
```
to fix this problem

**Comment by k-okada** [comment]
if you merge and recompile everything, you'll get same result https://github.com/jsk-ros-pkg/geneus/pull/31

**Comment by k-okada** [comment]
BTW, which message has such a huge const variable? each message has it'own package (not package, not roseus) and internal symbol table size is defined for each message.

**Comment by garaemon** [comment]
this is https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2015_06_hrp_drc/drc_com_common/msg/OCS2FCSmall.msg

**Comment by k-okada** [comment]
I see...

**Comment by k-okada** [comment]
I see...

**Comment by mmurooka** [comment]
I added 61th constant variable to this message file, and met this error.

I reverted and removed DOOR_DRC_LASVEGAS constant variable in https://github.com/jsk-ros-pkg/jsk_demos/pull/656...

**Comment by k-okada** [comment]
you don't have to revert that, please add new variable and try
https://github.com/jsk-ros-pkg/jsk_roseus/issues/313#issuecomment-101499461

if this works, i'll merge https://github.com/jsk-ros-pkg/geneus/pull/31 and if you update geneus, everything should working fine.

**Comment by k-okada** [comment]
also fixed in message generation level https://github.com/jsk-ros-pkg/geneus/pull/31

**Comment by mmurooka** [comment]
遅くなりましたが確認してなおりました。ありがとうございます。
closeしていただいて大丈夫です。

**Comment by mmurooka** [comment]
必要最小限かは分からないですが、
以下で更新が反映されて直ります。
drc_task_commonを最新にしたPCでは必ず必要です。

```
roscd geneus
git pull
source /opt/ros/hydro/setup.bash
catkin bt --start-with-this
source ~/.bashrc
roscd
rm -rf share/roseus/ros/drc_com_common/
roscd drc_com_common
catkin bt --start-with-this --force-cmake
```
