### ISSUE TITLE
:wait-for-result does not catch result correctly when we have to action client with same name?

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_roseus#462]
when there is two actionlib client for same controller it did not return from :wait-for-result, for example

```
*ri* . controller-actions
:head
:rarm
:larm
:head
```

did not work well

**Comment by furushchev** [comment]
related? https://github.com/jsk-ros-pkg/jsk_roseus/issues/407

**Comment by k-okada** [comment]
yeah, that is duplicates.

--
◉ Kei Okada
