### ISSUE TITLE
what is checked at `test-param-cached` in `roseus/test/param-test.l`

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_roseus#465]
@k-okada From just curiosity, what is assumed to be checked in the test case below?
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/test/param-test.l#L7

**Comment by k-okada** [comment]
@YoheiKakiuchi is the original author? may be forget to use
`get-param-cached` ?


--
◉ Kei Okada

**Comment by YoheiKakiuchi** [comment]
I don't remember when writing code.
@furushchev you can fix them.

**Comment by furushchev** [comment]
@k-okada @YoheiKakiuchi I see. This will be fixed at #467
