### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by pazeshun** [jsk-ros-pkg/jsk_roseus#524]
jsk_apc needs https://github.com/jsk-ros-pkg/jsk_roseus/pull/520

**Comment by k-okada** [comment]
good question, I'll release if
https://github.com/jsk-ros-pkg/jsk_roseus/pull/521 is merged.

--
◉ Kei Okada


2017-06-14 18:17 GMT+09:00 Shun Hasegawa <notifications@github.com>:

**Comment by k-okada** [comment]
done -> https://github.com/ros/rosdistro/pull/15322

**Comment by pazeshun** [comment]
Thanks!
